SuffolkLITLab/EfileProxyServer

- pom.xml
- src/main/java/edu/suffolk/litlab/efspserver/LegalIssuesTaxonomyCodes.java
- src/main/java/edu/suffolk/litlab/efspserver/XsdDownloader.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/DocassembleToFilingEntityConverter.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EfmCallback.java
- src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java
- src/main/java/tyler/efm/services/EfmFirmService.java
- src/main/java/tyler/efm/services/EfmUserService.java
Finally did some reading on how to do Java logging well*, I changed most of the interfaces to SLF4J (simple logging facade 4 java, names are horrible), which is just a standard interface on top of many different logging backends.
We still use Java common logging (JCL) under the hood, so nothing's changed there yet. But we have the flexibility to when we want to, say, if we need to start running multiple proxys and a load balancer to them, some distributed logging system would work much better in that case. But for now, this is good. 
Sorry @nonprofittechy, this might give you some merge conflicts if you've started doing stuff. It should be simple to fix though.
* I liked https://sematext.com/blog/java-logging/ a lot
> Replaced all java common logging with slf4j

- .gitignore
- docs/https.md
- src/main/config/ServerConfig.xml
- src/main/java/edu/suffolk/litlab/efspserver/HttpsCallbackHandler.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java
Server is now running in HTTPS!
I was debating trying to support both HTTP and HTTPS, but that might be a bit difficult, so I'm probably going to follow https://letsencrypt.org/docs/certificates-for-localhost/ and use that cert for localhost development (or modifying it to work with docker... not sure).
@nonprofittechy, the only resource I couldn't find to document was how you got the cert for the CA that signed ours. Would you mind just dropping that somewhere?
> HTTPS Implementation

- src/main/java/edu/suffolk/litlab/efspserver/codes/DataFieldRow.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/AddressDocassembleJacksonDeserializer.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/DocassembleToFilingEntityConverter.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/NameDocassembleDeserializer.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/PersonDocassembleJacksonDeserializer.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCaseTypeFactory.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializer.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java
- src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/CasesService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java
- src/main/java/edu/suffolk/litlab/efspserver/services/FilingError.java
- src/main/java/edu/suffolk/litlab/efspserver/services/InfoCollector.java
- src/test/java/edu/suffolk/litlab/efspserver/AddressTest.java
- src/test/java/edu/suffolk/litlab/efspserver/InfoCollectorTest.java
The results might be faster, but it does end up with much more clutter in the lower level functions. Result<..., FilingError> should still be present at the higher level Service functions, but everything else in the lower level should throw, since much of what we were doing before was to equivalent to catch and throw. 
Saves ~100 lines, so I guess that's not bad.
> DataField codes, and Throwing more exceptions instead of returning Results

- src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCaseTypeFactory.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfWsCallback.java
Not explicitly tested, but redundant regardless (also can't test until this gets merged and pushed to test/prod).
Fixes #38
> Show "return", not "reject", when court says to

- docker-compose.yml
- docs/https.md
- docs/setup.md
- env.example
- pom.xml
- src/main/config/ServerConfig.xml
- src/main/java/edu/suffolk/litlab/efspserver/ecf/PolicyCacher.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerModuleSetup.java
- src/main/java/edu/suffolk/litlab/efspserver/jeffnet/FilingInformationJeffNetSerializer.java
- src/main/java/edu/suffolk/litlab/efspserver/services/AcmeChallengePublisher.java
- src/main/java/edu/suffolk/litlab/efspserver/services/AcmeChallengeService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/AcmeChallengeWriter.java
- src/main/java/edu/suffolk/litlab/efspserver/services/AcmeRenewal.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EndpointReflection.java
- src/main/java/edu/suffolk/litlab/efspserver/services/PaymentsService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java
- src/test/java/edu/suffolk/litlab/efspserver/services/CodesServiceTest.java
[ACME (automatic certification management environment)](https://datatracker.ietf.org/doc/html/rfc8555#page-4) is standard that Lets Encrypt uses to automatically generated certificates for your site.  This PR lets you start a cert challenge from a separate program (`AcmeRenewal`), and then detect and publish the token from the main server. Flexible enough that it should be able to run on a timer automatically when you don't have to interactively agree to the terms of service.
Uses acme4j, with most of the `AcmeRenewal` class coming from https://shredzone.org/maven/acme4j/example.html.
Starts progress on #80, though it doesn't finish it; we still need to turn the`.pem` cert into a Java key store file, copy it
to the right place, restart the server so it can use the new cert, and then put …
> ACME/Lets Encrypt support + arbitrary ports

- .github/workflows/formatting.yml
- docs/wsdl2java.md
- src/main/java/edu/suffolk/litlab/efspserver/HeaderSigner.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCodesService.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfWsCallback.java
- src/main/java/edu/suffolk/litlab/efspserver/services/AuthenticationService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/CasesService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java
When trying to make a [tool to better facilitate searching through codes](https://github.com/SuffolkLITLab/docassemble-EFSPIntegration/issues/153), I quickly ran into the fact that our server doesn't allow cross-origin access from JS in the browser, which we might use for such a solution. There's no reason JS in the browser shouldn't be able to access any of the codes endpoints. 
The [solution from stackoverflow](https://stackoverflow.com/a/28996470/11416267) was what I went with.
It'd be a bit more complicated to try to allow e-filing submissions entirely through JS in the browser though, so I'm hesitant to dive into that.
> CORS handling on the codes

- src/main/java/edu/suffolk/litlab/efspserver/services/AcmeRenewal.java
I've had some issues with not getting LetEncrypt emails, and I really tried to see if there was any issues with how I was using the `acme4j` client, but I couldn't find anything wrong; we're already giving LetsEncrypt our email, so it should be working. Idk. I did [re-read the acme4j docs](https://shredzone.org/maven/acme4j/usage/login.html) and found some improvements that I could make, so I did. But nothing big got fixed from this. :(
> Verify acme email

- src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java
- src/main/java/edu/suffolk/litlab/efspserver/codes/CodeTableConstants.java
- src/main/java/edu/suffolk/litlab/efspserver/codes/CodeUpdater.java
- src/main/java/edu/suffolk/litlab/efspserver/codes/DataFieldRow.java
- src/main/java/edu/suffolk/litlab/efspserver/codes/FilingCode.java
- src/main/java/edu/suffolk/litlab/efspserver/codes/FilingComponent.java
- src/main/java/edu/suffolk/litlab/efspserver/codes/OptionalServiceCode.java
- src/main/java/edu/suffolk/litlab/efspserver/codes/PartyType.java
- src/main/java/edu/suffolk/litlab/efspserver/db/DatabaseVersion.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializer.java
- src/test/java/edu/suffolk/litlab/efspserver/codes/CodeDatabaseTest.java
- src/test/java/edu/suffolk/litlab/efspserver/db/DatabaseVersionTest.java
- src/test/java/edu/suffolk/litlab/efspserver/ecf/EcfCaseTypeFactoryTest.java
- src/test/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializerTest.java
Shrinks the code tables, particularly the optional services one, which required some refactoring to not assume that most operations take only a single transaction.
It shrinks the disk usage by a few GB, can't find my notes that I have for how much. It wasn't a ton though, and would need to go to enums if we wanted to actually decrease usage.
For now though, addresses #99.
Waiting for a run of `replaceAll` to finish for Illinois, then I'll merge, and will make the PR for integration tests as well.
> Smaller codes DB tables

- src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfWsCallback.java
Before, if they gave us nothing, the message would be "the document."
Now, we don't add "The document" unless there isn't anything already (in the cases where there aren't file names, but are comments).
> Assume that Tyler gives us nothing on Callback

- pom.xml
- src/main/java/edu/suffolk/litlab/efspserver/codes/OptionalServiceCode.java
- src/main/java/edu/suffolk/litlab/efspserver/db/DatabaseVersion.java
Despite the fact that there are two tables for optional services to shrink the disk space usage, there was an error that would duplicate entries in the table that should have been much smaller, but it would only happen on insert/ a version update for the court. No logical errors happened, but would result in a large amount of codes and extra parsing to be done on the docassemble side.
> Dedupe optionalservice table

- docs/https.md
- docs/tyler_codes.md
- src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java
* For https.md:
* linked directly to the code where things are implemented / the certs are used.
* moved a few comments to inline code comments
* For tyler_codes.md: 
* typos
* quick description of the hierarchy and example SQL queries
* filled in some more details about specific tables
See https://github.com/SuffolkLITLab/EfileProxyServer/issues/145#issuecomment-1674130420 and https://github.com/SuffolkLITLab/EfileProxyServer/issues/145#issuecomment-1699990387.
> More docs improvements

- src/main/java/edu/suffolk/litlab/efspserver/JsonHelpers.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingDocDocassembleJacksonDeserializer.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializer.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java
Individual filers don't have to provide filing attorneys, even if the court marks `FilingFilingAttorneyView` as required (it's only required form firm filers, something I hadn't noticed in the fine print of the documentation).
Adds an extra `getFirm` query when preparing filing, hopefully it doesn't take too long though.
> Allow for no Attorneys if individual filer

- src/main/java/edu/suffolk/litlab/efspserver/FilingInformation.java
- src/main/java/edu/suffolk/litlab/efspserver/LowerCourtInfo.java
- src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf4/Ecf4Filer.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf4/Ecf4Helper.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf4/EcfCaseTypeFactory.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf4/EcfCourtSpecificSerializer.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf4/OasisEcfWsCallback.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf4/PolicyCacher.java
- src/main/java/edu/suffolk/litlab/efspserver/ecf4/TylerModuleSetup.java
- src/main/java/edu/suffolk/litlab/efspserver/ecfcodes/CodeDatabaseAPI.java
- src/main/java/edu/suffolk/litlab/efspserver/ecfcodes/CodeUpdater.java
- src/main/java/edu/suffolk/litlab/efspserver/jeffnet/CourtsOnlyCodesService.java
- src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetModuleSetup.java
- src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/CodesService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/CourtSchedulingService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EfmCheckableFilingInterface.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EfmModuleSetup.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EndpointReflection.java
- src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CaseType.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CodeDatabase.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/EcfCodesService.java
- src/test/java/edu/suffolk/litlab/efspserver/ecf/EcfCaseTypeFactoryTest.java
- src/test/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializerTest.java
- src/test/java/edu/suffolk/litlab/efspserver/services/CodesServiceTest.java
> One more sphion

- docs/https.md
- src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java
- src/main/java/edu/suffolk/litlab/efspserver/services/acme/AcmeChallengePublisher.java
- src/main/java/edu/suffolk/litlab/efspserver/services/acme/AcmeChallengeService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/acme/AcmeChallengeWriter.java
- src/main/java/edu/suffolk/litlab/efspserver/services/acme/AcmeRenewal.java
About to renew certs on test and prod, going through and documenting the process, and decided to use the `MONITORING_EMAIL` over the `TYLER_USER_EMAIL`, given the tyler user email is my old email that might be going away.
Additionally moves the ACME files to a separate package in Services, and cleans up their javadocs a bit.
> Some last moving things for ACME

- src/main/java/edu/suffolk/litlab/efspserver/ecf4/EcfCourtSpecificSerializer.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CaseCategory.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CaseType.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CodeAndLocation.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CodeDatabase.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/EcfCodesService.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/FilingCode.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/OptionalServiceCode.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/PartyType.java
The flow goes like this:
1. To search for all filing types where the name has the words "Jury Demand" in
it, go to `/jurisdictions/<id>/codes/filing_types?search=Jury Demand`. These methods are called `search` internally.
2. From there, you'll get the full names of the codes. Take one of those full
names, say, "Jury Demand Filed - 12", and go to
`jurisdiction/<id>/codes/filing_types/Jury Demand Filed -12`. These methods are called `retrieve` internally.
3. There, you'll get the codes and locations that have that exact name. Go to
`jurisdictions/<id>/codes/courts/<location_id>/filing_types/12345` to get
the full filing codes.
Added for:
* Case Categories
* Case Types
* Filing Types
* Party Types
* Optional Services
> Search jurisdiction codes

- src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java
- src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java
- src/main/java/edu/suffolk/litlab/efspserver/services/SoapExceptionMapper.java
Make sure that we can properly get notifications for SOAP Fault exceptions that are thrown.
https://mincong.io/2018/12/03/exception-handling-in-jax-rs/ came in handy when writing it.
The `@Provider` tag by itself didn't work, but it is worthy of signaling, so I left it there.
> Use ExceptionMapper

- docs/operations_guide/index.md
- env.example
- fly_startup_script.sh
Should fix the nightly codes update when running from a continuous deployment built image.
> Support client_sign.properties as a secure file.

- src/main/java/edu/suffolk/litlab/efspserver/ecf4/Ecf4Filer.java
- src/main/java/edu/suffolk/litlab/efspserver/services/FilingError.java
- src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/EcfCodesService.java
Actually set the Exception class's message, so exception stack traces don't just say "null", and log as error when an error occurs when getting fees.
Minor fix: getting an individual category directly returned the Optional as JSON,  which is useless (only prints empty and present, from isEmpty and isPresent, lol).
> Better errors when there's a prepare filing error

- src/main/java/edu/suffolk/litlab/efspserver/ecfcodes/CodeUpdater.java
Attempts to resolve Tyler Code refresh issue.
We're changing it so when we try to delete data for a table that doesn't exist yet, it just skips it. It seems benign, but maybe we're missing some context. 
@BryceStevenWilley no pressure to review, just so you're aware!
> Ignore tables that don't exist

- pom.xml
In order to be more knowledgeable about any testing gaps we have, we want coverage metrics to be generated using [JaCoCo](https://www.eclemma.org/jacoco/) on each run of the unit (and any eventual Java-run integration) tests. This will help the ECF5 effort by finding gaps in unit tests and helping us do any necessary refactors for ECF5 more confidentially.
When revisiting the repo, I noticed that JaCoCo was not running as it should have been. When I initially wrote the project back in my Java-ignorant days, I had incorrectly setup the JaCoCo plugin in the `pom.xml`: it was configured in `<pluginManagement>`, but not in `<plugins>`. So, the config would be used in any child projects, but not in the project itself. Additionally, it adds the report to the `verify` phase, which occurs after …
> Re-enable coverage data on `mvn verify`

- src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetModuleSetup.java
The server should be able to run without that env var. Confirmed with a manual run that the server loads fine without the env var.
Using the autorun-coverage PR as the base branch, since it has the mockito version bump to make tests pass on my machine.
> Don't crash if JEFFERSON_ENDPOINT isn't there

- .github/workflows/build_and_test.yml
- README.md
- pom.xml
- src/test/java/edu/suffolk/litlab/efspserver/SoapClientChooserTest.java
- src/test/java/edu/suffolk/litlab/efspserver/db/DatabaseVersionTest.java
- src/test/java/edu/suffolk/litlab/efspserver/db/LoginDatabaseTest.java
- src/test/java/edu/suffolk/litlab/efspserver/db/UserDatabaseTest.java
- src/test/java/edu/suffolk/litlab/efspserver/services/CodesServiceTest.java
- src/test/java/edu/suffolk/litlab/efspserver/tyler/codes/CodeDatabaseTest.java
Mainly for us to not run tests that make a connection to Tyler servers in our CICD pipelines, as they will break unexpectedly.
Made because currently, the `SoapClientChooserTest` was failing in both #200 and #197, for reasons completely unrelated to those PRs. This should keep the CICD cleaner and more consistent.
> Start using JUnit's Tags to organize tests

- .github/workflows/build_and_test.yml
Not too much faster, but does save ~96MB of bandwidth from maven central on each run. Pretty nice.
~1/2 of the time is spent on compiling everything, ~1/2 is spent on tests (90% of the tests are `CodesServiceTest` and `DatabaseVersionTest`, the DB container tests that spin up a docker container for postgres.
> Add cache in workflow file

- Dockerfile
- fly_startup_script.sh
Installing and using AWS-cli in Jammy seems to be broken somehow, getting this error:
>  fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
I assume that it's a permission thing in S3 (not sure how it's acting different in a different image), but it's something I'll have to fix later. Revert to a working state.
> Revert change made in #207, and the alpine change in #206.

- .github/workflows/formatting.yml
- .gitignore
- CONTRIBUTING.md
- src/main/java/edu/suffolk/litlab/efspserver/Address.java
- src/main/java/edu/suffolk/litlab/efspserver/services/PaymentsService.java
* only one small formatting change affected the repo (text block start quote moved to beginning of line)
* can use the native graal image to format: faster startup / runtime
* 8 seconds vs 13 on main, and 31MB download vs 198 on main (for all of Java)
* don't need Java on the GitHub image / can run with java versions newer than 17
* added better help message in GitHub action when it fails (just saying what to do, instead of a file path with no context)
> Update to latest google-java-format (1.27.0)

- Dockerfile
- docs/adr/008-choice-of-rest-docs.md
- pom.xml
- proxyserver/enunciate.xml
- proxyserver/pom.xml
- proxyserver/src/main/java/edu/suffolk/litlab/efspserver/services/AuthenticationService.java
Generates a static site to describe endpoints, as well as making a swagger-ui version as well.
To test this:
* run `mvn compile`
* Bring up a local http server (node server or python http.server) in `proxyserver/target/enunciate-docs/apidocs` folder with `python -m http.server 8000` or [your language of choice](https://gist.github.com/willurd/5720255).
* Visit that URL in your browser (likely `127.0.0.1:8000`).
Enunciate:
Swagger:
Additional changes:
* Adds example [Enunciate annotations](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations) to an endpoint, just for an easy place to continue adding usage
* Updates ADR 8 with this updated decision
> Use Enunciate to generate REST endpoint docs

- .github/workflows/docs_site.yml
- docs/.nav.yml
- docs/developing.md
The relative links to https://projects.suffolklitlab.org/EfileProxyServer/endpoints/ and https://projects.suffolklitlab.org/EfileProxyServer/apidocs/ were broken (because GH pages deploys from a subpath, not at the root of the domain). 
Also adds the old documentation link somewhere. Docs need a rather large re-haul soon anyway.
> Fix relative links to the javadocs and enunciate pages

- .github/workflows/fly.yml
- Dockerfile
- dev-compose.yml
- docker-compose.yml
- proxyserver/pom.xml
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/RootService.java
- proxyserver/src/main/resources/version.properties
Only on the test server; will be null (and thus not visible) in production.
Adds passthrough args to several layers:
* the maven / Java layer (`-Dbuild.revision`)
* which is the part actually included in `version.properties` and ready by `RootService.java`
* if the commit property is null or empty, it's not shown on the about page
* Dockerfile
* done as an `ARG CI_COMMIT_SHA` in both stages of the build, set as a Docker label and passed to maven
* Docker compose 
* as a `build:args` in both. Works on cli as `CI_COMMIT_SHA=... docker compose build`.
* fly
* just the test deploy workflow, not the production one
> Put git commit in Manifest and on about page

- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/CodesService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/CourtsOnlyCodesService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/EcfCodesService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/JurisdictionServiceHandle.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/JurisdictionSwitch.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/services/CodesServiceTest.java
Added all codes endpoints to the abstract `CodesService` class so enunciate could pick them up for documentation. They are marked as `Unimplemented` in the JeffNet version (which is deprecated and will be removed soon anyway. I'll take the increase in boilerplate for the moment knowing that).
All of the implementations in `EcfCodesService` have been marked with `@Override` and had the JAX-RS annotations removed, but not functionality has changed. Confirmed that enunciate can pick up javadocs from classes earlier in the path. The `@responseExample` javadoc annotation isn't great, but gets the job done.
To keep the HATEOS stuff from completely breaking, I needed to also look through the parent class for annotations. It's a bit precarious, but tests still pass, and tbh, once the rest of the …
> Better Codes API docs

- pom.xml
Even though enunciate can parse the `responseExample` javadoc tag, we need to tell javadoc about it so it doesn't error.
> Add `responseExample` to custom javadoc tags

- proxyserver/pom.xml
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/EfspServer.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/utils/JsonExceptionMapper.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/services/AdminUserServiceTest.java
Found this by passing an invalid `RegistrationRequestType` to the `registerUser` endpoint (it needs to be all caps).
But for some reason, instead of erroring out, the server would return a 204, making it seem like some sort of user had been registered. Was able to track the 204 down to the fact that CXF catches IOExceptions (JAXRSInvoker.java:L287), which the JSON exception is considered a part of, but there were no exception handlers to handle the exception, so it was treated as empty.
The fix involved making an exception handler to properly handle and category the exception as a user input exception (400).
Also added a unit test on the AdminUserService as a regression test for this. Had to update mockito to mock static methods, and refactored a small bit of the EfspServer setup into a …
> Handle JSON parsing errors reasonably

- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/setup/tyler/OasisEcfWsCallback.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/setup/tyler/OasisEcfv5WsCallback.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/setup/tyler/TylerModuleSetup.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/ecf4/EcfCaseTypeFactoryTest.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/ecf4/EcfCourtSpecificSerializerTest.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/ecf4/ReviewedFilingExamples.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/setup/tyler/OasisEcfWsCallbackTest.java
* Remove all of the possible document binaries (the main point of this PR)
* was previously only removing the main document binary from the lead document; now removes all document renditions from lead and connected documents.
* this is interfering with the logs; the document binaries are too big and seem to prevent other valid logs from those requests from showing up. Considered taking out all of the XML object printing, but some are still needed for debugging. Will work on bringing those down in the future.
* use log formatting when possible
* slight renaming of methods
* All of the refactoring necessary to enable the above
* using suppliers in constructors
* mocking out Tyler / database stuff to actually test the class with jqwik.
> Notify Filing Review Complete Logs are too big

- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/EfspServer.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/utils/ObservabilityHeadersInterceptor.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/utils/ObservabilityResetInterceptor.java
- proxyserver/src/main/resources/logback.xml
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/utils/ObservabilityHeadersInterceptorTest.java
Makes the switch over to JAX-RS compliant container filters, which are better because:
* The CXF API is incomprehensible; very difficult to find the right random string to get from the message, and very little documentation in the code about what each entry contains, when it will be there. I tried implemening this change previously with the CXF API, but both the response code and path were null. idk why, and didn't want to spend ages trying to figure it out.
* we can eventually switch the HTTP server over to Spring (if desired; would clean up a bit of stuff: related to https://github.com/SuffolkLITLab/EfileProxyServer/blob/main/TODO.md).
https://stackoverflow.com/a/46726824/11416267
> Show return status to all calls where our logic runs

- .github/workflows/build_and_test.yml
Had we been doing this, we could have prevented the need for #291 and caught it CI.
Uses a different build because the docker build is completely separate from the local java build
> Try building the docker file in CI

- TylerEfmClient/src/main/java/edu/suffolk/litlab/efsp/tyler/TylerEnv.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/docassemble/DocassembleToFilingInformationConverter.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/docassemble/FilingInformationDocassembleJacksonDeserializer.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/CodeUpdater.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/CodeDatabase.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/EfspServer.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/auth/SecurityHub.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/auth/TylerLogin.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/ecf4/SoapClientChooser.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/AdminUserService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/CasesService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/CourtSchedulingService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/FirmAttorneyAndServiceService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/PaymentsService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/setup/tyler/Ecf4Filer.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/setup/tyler/TylerModuleSetup.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/utils/UpdateCodeVersions.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/db/DatabaseVersionTest.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/docassemble/DocassembleToFilingInformationConverterTest.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/CodeDatabaseTest.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/auth/SecurityHubTest.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/ecf4/EcfCaseTypeFactoryTest.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/services/AdminUserServiceTest.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/services/CodesServiceTest.java
I.e., anytime we read the env var, immediately turn it into the enum. Throws a quick `IllegalArgumentExeception` at those points, so the server should immediately stop if invalid.
* also exposes the hack that the JSON parser depends on if Tyler's env is stage or prod. This is something that we still need to resolve elsewhere, but at least we aren't grabbing env vars deep inside that class anymore.
The only place that could have had more refactorings but didn't was `SoapClientChooser`. Could have introduced a String jurisdiction TylerEnv object to handle the mappings instead of a single string, but I would have had to retype all of the jurisdiction keys, which would have meant potential unnecessary errors.
A second attempt at #293, which got too big (had tried to include jurisdiction to …
> Use `TylerEnv` on all parsing boundaries

- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/EfspServer.java
Wonderful choice by me only a few months ago to pass null instead of the TylerEnv to the CodeDatabase when starting up, just to make tables; switching to an actual object means we null pointer exeption immediately.
Not sure how no tests didn't catch this, will need to fix that.
Fixes introduced in #296
> Don't pass nulls instead of env

- proxyserver/src/main/java/edu/suffolk/litlab/efsp/docassemble/JsonExtractException.java
Just needed to pass the throwable to the parent class.
> Better JsonExtractException stacktraces

- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/CodeDatabaseAPI.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/CodeUpdater.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/CodeDatabase.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/OptionalServiceCode.java
Instead of `CodeListDocuments`.
https://github.com/SuffolkLITLab/EfileProxyServer/pull/302
Moving towards not having the full document available (i.e. partial parsing of the XML, so we don't get OOM errors when we try to load the 831MB XML files that Tyler sends us). The new version and iterators (not iterables, which could be rerun multiple times, as these are streams of remote data, re-running them multiple times would mean downloading the same info multiple times).
Also actually starts using the `CodeDatabaseAPI`, which wasn't really used before this.
> Change CodeDatabaseAPI to work on Iterator<Map> 

- proxyserver/src/test/java/edu/suffolk/litlab/efsp/db/DatabaseVersionTest.java
They are included in the gitignore, but confusing when they just hang around.
> Remove testing related files after tests finish

- proxyserver/src/main/java/edu/suffolk/litlab/efsp/docassemble/FilingInformationDocassembleJacksonDeserializer.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/docassemble/PersonDocassembleJacksonDeserializer.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/ecf4/CoreMessageAndNames.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/CasesService.java
* Nullable annotation update from `javax` to `jakarta`.
* Use existing `setupServicePort` function instead of duplicating logic involving headers
* Got rid of unused filter attribute when parsing people
> Misc code changes

- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/CaseCategory.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/CaseType.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/CodeDatabase.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/FilingCode.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/OptionalServiceCode.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/tyler/PartyType.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/EfspServer.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/EcfCodesService.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/utils/EnumExceptionMapper.java
- proxyserver/src/main/java/edu/suffolk/litlab/efsp/stdlib/SQLGetter.java
- proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/services/CodesServiceTest.java
Would allow a new param to let you either get all of the search results for a string, or would let you get courts that a particular search query would be sufficient for partial matches with.
Turns a custom python script that takes 150 seconds to run into a single query that can be added to the codes interview to give detailed information about a particular search string. That query will be added once this is in stage.
> Adding court coverage to code search endpoints
