SuffolkLITLab/EfileProxyServer

pom.xml, src/main/java/edu/suffolk/litlab/efspserver/SendMessage.java
Still getting the hang of this but this should be a safe addition. If you don't have time to review I can just merge.
=> Add MVP message handling

Dockerfile, pom.xml, src/main/java/edu/suffolk/litlab/efspserver/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/DatabaseInterface.java, src/main/java/edu/suffolk/litlab/efspserver/EfmClient.java, src/main/java/edu/suffolk/litlab/efspserver/FilingDoc.java, src/main/java/edu/suffolk/litlab/efspserver/FilingInformation.java, src/main/java/edu/suffolk/litlab/efspserver/LegalIssuesTaxonomyCodes.java, src/main/java/edu/suffolk/litlab/efspserver/Person.java, src/main/java/edu/suffolk/litlab/efspserver/Transaction.java, src/main/java/edu/suffolk/litlab/efspserver/UserDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/XmlHelper.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeTableConstants.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetFiler.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/PersonJeffNetJacksonSerializer.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfmFilingInterface.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/OasisEcfFiler.java, src/test/java/edu/suffolk/litlab/efspserver/UserDatabaseTest.java, src/test/java/edu/suffolk/litlab/efspserver/jeffnet/FilingInformationToJeffNetTest.java
Added the User Database that holds info about users so we can send them filing status updates.
Going to commit, more changes to this have been made in later branches.
=> User database

docs/adr/001-java-cxf-for-soap.md, docs/adr/002-build-project-with-maven.md, docs/adr/003-use-postgres-as-database.md, docs/adr/004-use-javax-rs-for-rest-api.md, docs/adr/005-use-jackson-to-convert-json.md, docs/adr/006-slf4j-as-logger-and-jdk-backing.md, docs/adr/README.md, docs/adr/template.md, docs/setup.md, pom.xml
I came across https://18f.gsa.gov/2021/07/06/architecture_decision_records_helpful_now_invaluable_later/, which is something I've been meaning to do better with this project: actually record the decisions about which framework / library to use, etc. Maybe some actual software architecture decisions can be recorded as well.
=> Architecture Decision Records + Documentation

src/main/java/edu/suffolk/litlab/efspserver/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/DatabaseInterface.java, src/main/java/edu/suffolk/litlab/efspserver/UserDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/AddressDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/DocassembleToFilingEntityConverter.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingDocDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/PersonDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetFiler.java, src/main/java/edu/suffolk/litlab/efspserver/services/AllWrongCollector.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java, src/main/java/edu/suffolk/litlab/efspserver/services/ExtractError.java, src/main/java/edu/suffolk/litlab/efspserver/services/FailFastCollector.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/InfoCollector.java, src/main/java/edu/suffolk/litlab/efspserver/services/InterviewToFilingEntityConverter.java, src/main/java/edu/suffolk/litlab/efspserver/services/InterviewVariable.java, src/main/resources/logging.properties, src/test/java/edu/suffolk/litlab/efspserver/InfoCollectorTest.java, src/test/java/edu/suffolk/litlab/efspserver/UserDatabaseTest.java, src/test/java/edu/suffolk/litlab/efspserver/services/DocassembleToFilingEntityConverterTest.java
Is eventually going to become the "author mode" of an interview: if in author mode, DA will call the proxy, and we'll give back all of the variables you're still missing (right now just to convert to the POJOs, but eventually we'll go all the way through to the EfmFilerInterfaces). If not in Author mode, the DA interview will fail gracefully until someone can fix it.
This one is pretty big and important, so I'm going to go through and review myself before I merge for sure.
=> Added REST query for the `check` of an existing interview.

src/main/java/edu/suffolk/litlab/efspserver/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/EfmClient.java, src/main/java/edu/suffolk/litlab/efspserver/Transaction.java, src/main/java/edu/suffolk/litlab/efspserver/UserDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/FilingInformationJeffNetSerializer.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetFiler.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfmFilingInterface.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/services/OasisEcfWsCallback.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java, src/main/java/oasis/names/tc/legalxml_courtfiling/wsdl/webservicesprofile_definitions_4_0/FilingAssemblyMDEPort_FilingAssemblyMDEPort_Server.java, src/main/java/tyler/efm/wsdl/webservicesprofile_implementation_4_0/FilingReviewMDEService.java, src/test/java/edu/suffolk/litlab/efspserver/UserDatabaseTest.java
Left undone: how does Tyler actually know what service / port / endpoint to call for the callback? I'm assuming that it's the SendingMDEProfile, but I haven't tested, need to be able to send a document first, then test later.
=> New SOAP callback Service

README.md, pom.xml, src/main/java/edu/suffolk/litlab/efspserver/DatabaseInterface.java, src/main/java/edu/suffolk/litlab/efspserver/EfmClient.java, src/main/java/edu/suffolk/litlab/efspserver/LoginDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/SecurityHub.java, src/main/java/edu/suffolk/litlab/efspserver/UserDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/XsdDownloader.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerLogin.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetLogin.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfmCheckableFilingInterface.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfmFilingInterface.java, src/main/java/edu/suffolk/litlab/efspserver/services/FirmAttorneyAndServiceService.java, src/main/java/edu/suffolk/litlab/efspserver/services/LoginInterface.java, src/main/java/edu/suffolk/litlab/efspserver/services/NeverSubmitCollector.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java, src/test/java/edu/suffolk/litlab/efspserver/LoginDatabaseTest.java
DA client now needs just 1 token (made from the LoginDatabase main function).
It handles logging into Tyler and JeffNet (you pass in the token, so more
flexible there).
=> Added a security layer that handles tokens for all services

docs/setup.md, src/main/java/edu/suffolk/litlab/efspserver/LoginDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/SecurityHub.java, src/main/java/edu/suffolk/litlab/efspserver/UserDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetFiler.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetLogin.java, src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java, src/test/java/edu/suffolk/litlab/efspserver/LoginDatabaseTest.java
Wasn't properly forwarding errors from filing docs
=> More specific about tokens vs keys, small bugs

src/main/java/edu/suffolk/litlab/efspserver/SecurityHub.java, src/main/java/edu/suffolk/litlab/efspserver/SendMessage.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/db/DatabaseInterface.java, src/main/java/edu/suffolk/litlab/efspserver/db/LoginDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/db/LoginInfo.java, src/main/java/edu/suffolk/litlab/efspserver/db/MessageInfo.java, src/main/java/edu/suffolk/litlab/efspserver/db/MessageSettingsDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/db/Transaction.java, src/main/java/edu/suffolk/litlab/efspserver/db/UserDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfWsCallback.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetRestCallback.java, src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java, src/main/java/edu/suffolk/litlab/efspserver/services/CasesService.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/MessageSettingsService.java, src/main/java/edu/suffolk/litlab/efspserver/services/OrgMessageSender.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java, src/test/java/edu/suffolk/litlab/efspserver/CodeDatabaseTest.java, src/test/java/edu/suffolk/litlab/efspserver/LoginDatabaseTest.java, src/test/java/edu/suffolk/litlab/efspserver/UserDatabaseTest.java
Made the email settings settable through an API. They have to be, since we are now handling emails from different orgs all on the same server.
=> Email template

src/main/java/edu/suffolk/litlab/efspserver/EfmClient.java, src/main/java/edu/suffolk/litlab/efspserver/SecurityHub.java, src/main/java/edu/suffolk/litlab/efspserver/db/LoginDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/db/LoginInfo.java, src/main/java/edu/suffolk/litlab/efspserver/db/MessageSettingsDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerLogin.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetFiler.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetLogin.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetRestCallback.java, src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java, src/main/java/edu/suffolk/litlab/efspserver/services/CasesService.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfmFilingInterface.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/FirmAttorneyAndServiceService.java, src/main/java/edu/suffolk/litlab/efspserver/services/LoginInterface.java, src/main/java/edu/suffolk/litlab/efspserver/services/OrgMessageSender.java, src/main/java/edu/suffolk/litlab/efspserver/services/PaymentsService.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceContactInput.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java, src/test/java/edu/suffolk/litlab/efspserver/LoginDatabaseTest.java
61/66 endpoints implemented, and 51 are tested end to end. 
Need to review a bit before I merge, lots of changes here.
=> Filled in a lot of the REST API

.gitignore, Dockerfile, docs/wsdl2java.md, pom.xml, src/main/java/edu/suffolk/litlab/efspserver/EfmClient.java, src/main/java/edu/suffolk/litlab/efspserver/XsdDownloader.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeTableConstants.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/codes/FileType.java, src/main/java/edu/suffolk/litlab/efspserver/db/LoginDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCaseTypeFactory.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializer.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfWsCallback.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerLogin.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerModuleSetup.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetFiler.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetModuleSetup.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetRestCallback.java, src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfmModuleSetup.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java, src/main/java/edu/suffolk/litlab/efspserver/services/OrgMessageSender.java
As well as some misc changes to the REST API / Tyler filing side that can just be merged.
@nonprofittechy, shouldn't get in your way for merging, but let me know if it does.
=> Run with Jeffnet only + Updated JeffNet callback Message

src/main/java/ecfv5/https/docs_oasis_open_org/legalxml_courtfiling/ns/v5_0/wsdl/courtschedulingmde/CourtSchedulingMDE_Service.java, src/main/java/edu/suffolk/litlab/efspserver/FilingDoc.java, src/main/java/edu/suffolk/litlab/efspserver/FilingInformation.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingDocDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCaseTypeFactory.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerModuleSetup.java, src/main/java/edu/suffolk/litlab/efspserver/services/CourtSchedulingService.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java
Still can't complete a call because of: 
```
Caused by: javax.xml.bind.MarshalException
efspjava_1  |  - with linked exception:
efspjava_1  | [com.sun.istack.SAXException2: Object "id-b7121e91-f2e2-4f0f-87a7-773e075fd709" is found in an IDREF property but this object doesnt have an ID.]
```
But I can't figure that out yet, merging for now anyway.
=> Small fixes to the CourtSchedulingService

pom.xml, src/main/java/edu/suffolk/litlab/efspserver/SendMessage.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/db/DatabaseInterface.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerModuleSetup.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetModuleSetup.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfmModuleSetup.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/UpdateCodeVersions.java
* Added Quartz Scheduling for downloading the codes because it's solid for doing tasks at specific times
* Also fixed the Cancel 500 bug: was because of a missing object definition in a constructor
=> Scheduler for Code updating, and fixed Constructor

src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java
I checked that it at least passes the build stage
=> Change method to POST, renamed getFilingFees to calculateFilingFees

src/main/java/edu/suffolk/litlab/efspserver/codes/CourtLocationInfo.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializer.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/services/CourtSchedulingService.java, src/main/java/edu/suffolk/litlab/efspserver/services/Ecfv5XmlHelper.java
* allowreturndate was getting the wrong value from the court table
* was still using the wrong variable to distinguish between initial and subsequent filings
* fixed an issue with 0 indexd java Calendar objects vs 1 indexed java LocalDateTime/ LocalDate objects
* added always making a motion element, but nothing was fixed on the return date side. Still waiting for Tyler reply.
=> Misc Fixes to Prep the way for Return Date

src/main/java/edu/suffolk/litlab/efspserver/codes/CaseType.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CourtLocationInfo.java, src/main/java/edu/suffolk/litlab/efspserver/codes/FilingCode.java, src/main/java/edu/suffolk/litlab/efspserver/codes/NameAndCode.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializer.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/services/CodesService.java, src/main/java/edu/suffolk/litlab/efspserver/services/CourtSchedulingService.java, src/main/java/edu/suffolk/litlab/efspserver/services/Ecfv5XmlHelper.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingResult.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java, src/test/java/edu/suffolk/litlab/efspserver/codes/CodeDatabaseTest.java
* Fixes to ReturnDate
* Fixes to Reserve Court Date Sync
* another update to filing type
* more restrictions on initial vs subsequent filing types
=> Misc Updates, in commits

Dockerfile, env.example, pom.xml, src/main/java/edu/suffolk/litlab/efspserver/FilingInformation.java, src/main/java/edu/suffolk/litlab/efspserver/PartyId.java, src/main/java/edu/suffolk/litlab/efspserver/Person.java, src/main/java/edu/suffolk/litlab/efspserver/XmlHelper.java, src/main/java/edu/suffolk/litlab/efspserver/db/LoginDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/db/NewTokens.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingDocDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/FilingInformationDocassembleJacksonDeserializer.java, src/main/java/edu/suffolk/litlab/efspserver/docassemble/JsonHelpers.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCaseTypeFactory.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCourtSpecificSerializer.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/Ecfv5CaseTypeFactory.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java, src/main/java/edu/suffolk/litlab/efspserver/services/CasesService.java, src/main/java/edu/suffolk/litlab/efspserver/services/CourtSchedulingService.java, src/main/java/edu/suffolk/litlab/efspserver/services/Ecfv5XmlHelper.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/SecurityHub.java, src/test/java/edu/suffolk/litlab/efspserver/LoginDatabaseTest.java
Probably too many commits, because of testing on prod.
* stopped running tests on prod, because there have been quite a few times where maven on AWS freezes up, not super clear why, possibly too much memory usage but it's hard to tell TBH
* made a NewTokens object so it could be returned with XML, but TBH, it's not super useful, because it adds extra layers to the JSON that I can't really get rid of. Should reconsider all possible targets
* explicitly don't add Timezones to Date, which Tyler doesn't seem to like, despite it being allowed in XML (https://stackoverflow.com/questions/6143224/how-do-i-represent-dates-without-the-timezone-using-apache-cxf)
* lets you add and set attorneys from existing users
* don't crash if media type isn't passed
=> Return date in

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/new_feature.md, .github/workflows/build_and_test.yml, src/test/java/edu/suffolk/litlab/efspserver/services/CodesServiceTest.java
We run a maven tests and build on every commit now. Yay! Takes a minutes to complete, not sure how we can make that faster at all.
=> Added github issue templates and corrected codes service test

src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java, src/main/java/edu/suffolk/litlab/efspserver/services/FirmAttorneyAndServiceService.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java
=> Register user to a POST, return correct HTTP for attach serv contact

src/main/java/edu/suffolk/litlab/efspserver/ecf/EcfCaseTypeFactory.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetFiler.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfmFilingInterface.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java
Fix #50, by making it clear that the end date is exclusive, something not
mentioned by Tyler in the docs or by the Niem value.
=> Change end_date param to before_date

src/main/java/edu/suffolk/litlab/efspserver/Name.java, src/main/java/edu/suffolk/litlab/efspserver/db/DatabaseVersion.java, src/main/java/edu/suffolk/litlab/efspserver/db/Transaction.java, src/main/java/edu/suffolk/litlab/efspserver/db/UserDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/CoreMessageAndNames.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfWsCallback.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfv5WsCallback.java, src/main/java/edu/suffolk/litlab/efspserver/jeffnet/JeffNetRestCallback.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingResult.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/OrgMessageSender.java, src/test/java/edu/suffolk/litlab/efspserver/db/UserDatabaseTest.java
Generates the case title from the party names, or gets the existing
case title. Also gets the human readable court and case type names, not the
codes.
Fixes #54
=> Add case_title as template var/court and case type names

LICENSE, client_sign.properties.example, docker-compose.yml, docs/https.md, env.example, src/main/config/ServerConfig.xml, src/main/java/edu/suffolk/litlab/efspserver/services/AcmeRenewal.java, src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java, src/main/java/edu/suffolk/litlab/efspserver/services/EfspServer.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java
Process fully works, no more manually running keytool and openssl and copying around certs. Still have to manually run the process, but that'll be improved.
Process is documented in `https.md`.
Closes #80.
=> Letsencrypt pt2

docker-compose.yml, docker_run_script.sh, pom.xml, src/main/java/edu/suffolk/litlab/efspserver/StdLib.java, src/main/java/edu/suffolk/litlab/efspserver/TylerUserNamePassword.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/codes/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/OasisEcfFiler.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerModuleSetup.java, src/main/java/edu/suffolk/litlab/efspserver/services/AdminUserService.java, src/main/java/edu/suffolk/litlab/efspserver/services/CasesService.java, src/main/java/edu/suffolk/litlab/efspserver/services/CourtSchedulingService.java, src/main/java/edu/suffolk/litlab/efspserver/services/ServiceHelpers.java, src/main/java/edu/suffolk/litlab/efspserver/services/UpdateCodeVersions.java, src/main/resources/logback.xml, src/main/resources/logging.properties
Overall work to try to get Texas codes to download faster. The last few tries have completed in < 1 hour, which is good enough for me, as long as it doesn't take 3+ hours.
=> Parallel work

src/main/java/edu/suffolk/litlab/efspserver/db/DatabaseVersion.java, src/main/java/edu/suffolk/litlab/efspserver/services/UpdateCodeVersions.java
Earlier patch that I intended to already put on prod was wrong (put a table in the wrong database); this fixes it by a newer DB version.
=> Fix dbversion

src/main/java/edu/suffolk/litlab/efspserver/codes/CodeUpdater.java, src/main/java/edu/suffolk/litlab/efspserver/ecf/TylerModuleSetup.java
Had to use this class a lot recently when trying to debug things like `refundreason` not actually downloading. The issue was that as a thing to download, it's just not in the Policy at all, it's only showing up in the versions list. We can't
assume they'll be the same anymore, and I had to code around a bit of that.
=> Clean code updater

docs/setup.md, env.example
Address the comments in #145, but shouldn't close it (I believe plocket will take other notes in that issue as well).
=> Started improving setup.md

src/main/java/edu/suffolk/litlab/efspserver/services/CasesService.java
See https://cxf.apache.org/docs/client-http-transport-including-ssl-support.html#ClientHTTPTransport(includingSSLsupport)-HowtoconfiguretheHTTPConduitfortheSOAPClient
On Texas Stage, it took ~2 minutes to search, so 3 minutes should be good enough to avoid timeout issues.
Fixes #146.
=> Correctly set timeout for CaseSearch calls

src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CodeDatabase.java
Continue the job that 593d547e3ec0d3 only did part way.
Fix #53, for real this time.
=> Allow parent court fallback for all datafields

src/main/java/edu/suffolk/litlab/efspserver/CaseServiceContact.java, src/main/java/edu/suffolk/litlab/efspserver/FilingAttachment.java, src/main/java/edu/suffolk/litlab/efspserver/FilingInformation.java, src/main/java/edu/suffolk/litlab/efspserver/Person.java, src/main/java/edu/suffolk/litlab/efspserver/db/DatabaseVersion.java, src/main/java/edu/suffolk/litlab/efspserver/db/LoginDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/db/MessageSettingsDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/db/Transaction.java, src/main/java/edu/suffolk/litlab/efspserver/db/UserDatabase.java, src/main/java/edu/suffolk/litlab/efspserver/ecf4/EcfCaseTypeFactory.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingError.java, src/main/java/edu/suffolk/litlab/efspserver/services/FilingReviewService.java, src/main/java/edu/suffolk/litlab/efspserver/services/InterviewVariable.java, src/main/java/edu/suffolk/litlab/efspserver/services/PaymentsService.java, src/main/java/edu/suffolk/litlab/efspserver/services/UpdateCodeVersions.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CaseCategory.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CaseType.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/ComboCaseCodes.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CourtLocationInfo.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/CrossReference.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/DocumentTypeTableRow.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/FileType.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/FilerType.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/FilingComponent.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/OptionalServiceCode.java, src/main/java/edu/suffolk/litlab/efspserver/tyler/codes/PartyType.java
=> Fix issue affecting MetroSouth make lower_court_code an optional value

CONTRIBUTING.md, README.md
And link to CONTIBUTING.md from README.md.
Noticed this when working with @nonprofittechy earlier tonight.
=> Accurate formatting docs

fly.production.toml, fly.toml
PR to let CI/CD validate, as well as any interested reviewers. Very simple bump, so shouldn't be a big deal to merge. I'll do that tomorrow to give this a chance to gather any comments.
=> Bump to 8 GB machines in preparation for higher traffic.

Dockerfile, README.md, docs/adr/README.md, docs/setup.md, env.example
- Remove "-alpine" from maven version
- Remove em-dash from env var
- Tweak setup instructions, etc.
=> Update and tweak setup files and instructions

docs/architecture.md, docs/https.md, proxyserver/enunciate.xml, proxyserver/src/main/java/edu/suffolk/litlab/efspserver/services/AuthenticationService.java, proxyserver/src/main/java/edu/suffolk/litlab/efspserver/tyler/TylerLogin.java
Merging up older branches from @plocket. Thanks!
=> Slight improvements to internal comments/docs from dev experience

.github/workflows/build_and_test.yml, proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/AdminUserService.java
First, making it so those show up in PRs too, then remove the source of the error (using `<` tags as a template replacement in doc strings).
=> Fix javadoc error

docs/rest_guide.md
A big old long example of the filing payload. TODO: should establish that in a unit test, not the huge versions.
=> Review filing guide

.github/workflows/build_and_test.yml, .github/workflows/formatting.yml, TylerEcf4/pom.xml, TylerEcf5/pom.xml, TylerEfmClient/pom.xml, TylerEfmClient/src/main/java/edu/suffolk/litlab/efsp/tyler/Conversion.java, TylerEfmClient/src/main/java/edu/suffolk/litlab/efsp/tyler/TylerFirmClient.java, TylerEfmClient/src/main/java/edu/suffolk/litlab/efsp/tyler/TylerUserClient.java, TylerEfmClient/src/test/java/edu/suffolk/litlab/efsp/tyler/ConversionTest.java, TylerEfmClient/src/test/java/edu/suffolk/litlab/efsp/tyler/TylerClientsTest.java, docs/developing.md, pom.xml, proxyserver/pom.xml
Fixes #248. Just added the formatting to the pom file and ran `mvn spotless:apply`.
=> Spotless formatting

TylerEcf4/pom.xml, TylerEcf5/pom.xml, TylerEfmClient/pom.xml, pom.xml, proxyserver/pom.xml
Biggest change this round: internal package reorganizing.
=> Bump version to 1.2.17

proxyserver/src/main/java/edu/suffolk/litlab/efsp/tyler/TylerErrorCodes.java
Things like "user authentication failed" (i.e. bad password), "email address already in use", "no username", or common issues when logging in or registering an account.
Fix #233.
=> Don't error log on expected/common Tyler errors

proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/FilingReviewService.java
Was always a horrible crutch when trying to actively respond to efiling errors. Now that we pass in the session id / request id, it should be easier to get full error information about a docassemble interview.
Look at https://github.com/SuffolkLITLab/EfileProxyServer/pull/268/files?w=1 to get a better view of the diff (without whitespace).
=> Stop logging all vars

docs/rest_guide.md, proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/PaymentsService.java
As well as written descriptions in the `rest_guide.md`.
Only addition to the code file were javadocs and changing one out of date URI in an error response.
=> Added documentation to the payment endpoints

proxyserver/src/main/java/edu/suffolk/litlab/efsp/db/LoginDatabase.java, proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/EfspServer.java, proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/auth/SecurityHub.java, proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/services/AuthenticationService.java, proxyserver/src/test/java/edu/suffolk/litlab/efsp/db/LoginDatabaseTest.java, proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/auth/SecurityHubTest.java, proxyserver/src/test/java/edu/suffolk/litlab/efsp/server/services/AdminUserServiceTest.java, proxyserver/src/test/resources/logback.xml
Need this to be in place to verify any behavior changes that might come into play because of #228. Did some additional refactoring (like moving the `login` function to `SecurityHub`, where it makes more sense than the `LoginDatabase`; it was a lot of important, non-database logic in there).
=> Better security hub tests

proxyserver/src/main/java/edu/suffolk/litlab/efsp/ecfcodes/CodeUpdater.java, proxyserver/src/main/java/edu/suffolk/litlab/efsp/server/utils/UpdateCodeVersions.java
* Using MDC keys like `user` and `session` for context specific things:
* `user` is the jurisdiction, i.e. Massachusetts or Illinois
* `session` is the court location, i.e. `adams`
* `request` is the specific codes table, i.e. `partytype`, etc.
* Better variable name and reporting on the time took (incremental as well as total duration).
=> Better logs when doing code updates
